Poll frequency to find element
2gis/contesto pull request #124
Opened 2018-05-16 04:53 UTC by erview

2018-05-16 06:40 UTC, pishchalnikov requested changes

2018-05-16 06:40 UTC, pishchalnikov commented on contesto/core/finder.py
> +def find_element(obj, locator, timeout=None, poll_frequency=None):
None ставить нельзя. Только int или float

2018-05-16 06:40 UTC, pishchalnikov commented on contesto/core/finder.py
> +def find_elements(obj, locator, timeout=None, poll_frequency=None):
Здесь соответственно тоже, либо int, либо float.

2018-05-17 03:20 UTC, skyline-gleb approved these changes

2018-05-17 05:10 UTC, pishchalnikov approved these changes

2018-05-17 06:16 UTC, merged